### ISSUE TITLE
Fix playback of ongoing recordings

### ISSUE THREAD

**Issue by manuelm** [manuelm/pvr.dvbviewer#11]
_From @manuelm on April 23, 2016 13:5_

see #34 

_Copied from original issue: kodi-pvr/pvr.dvbviewer#35_

**Comment by Saschman** [comment]
Hi, ist there a Chance that this will be fixed?

BR

**Comment by manuelm** [comment]
Probably not in the near future. This is very low priority for me. I barley have time to work on #21 (none in the last 2.5 weeks) which is way more important.
