### ISSUE TITLE
grouping by recording directory not working

### ISSUE THREAD

**Issue by payback007** [manuelm/pvr.dvbviewer#13]
Hi all,

after update to Kodi v17 the grouping by recording directory is not working any more.

working: Grouping by
- first letter
- channel

not working: Grouping by
- recording directory
- series

Has anyone an idea what I configured wrong?

Thanks and best regards!

**Comment by manuelm** [comment]
Fixed: https://github.com/manuelm/pvr.dvbviewer/commit/d34bb49d3ad24acae5d6844c6c121182cdc2f6a6
