### ISSUE TITLE
Unicode in DMS EPG

### ISSUE THREAD

**Issue by SteenKA** [manuelm/pvr.dvbviewer#15]
I am Delphi in the DVBViewer forum and responsible for importing XMLTV EPG into the DVBViewer Media Server (DMS).

Seems to work fine in KODI, except for one minor thing:

If star-rating is present in the XMLTV file I use the unicode characters ★☆. In KODI they display as aquares.

The EPG from DMS is delivered as a UTF-8 encoded xml file.

Are characters in the EPG converted to the local codepage?

Or is there a setting?

![kodiepg](https://user-images.githubusercontent.com/22668516/27872996-eab57fea-61aa-11e7-8886-742240aa8e66.jpg)

**Comment by manuelm** [comment]
I already took a look at my code and the PVR is not doing any further encoding or charset conversion. Plot get's copied in https://github.com/manuelm/pvr.dvbviewer/blob/master/src/DvbData.cpp#L170 and passed to Kodi.

Since characters outside the ascii range work (e.g. the é in Khloé) it might be a font issue. Like the font doesn't have a star character. I'm not sure which font the default skin is using.

**Comment by manuelm** [comment]
Looks like the default font (NotoSans) of the default skin (estuary) doesn't support the star characters. If you change the skins font to Arial in Settings > Skin > Fonts the star characters are correctly shown.

**Comment by SteenKA** [comment]
Thanks. However, i could not find the font setting. I am a newbie, remember.
I tried: click the "gears" icon at the main menu, then skin settings. Nothing here.

**Comment by manuelm** [comment]
You need to switch to Advanced or Expert first. http://kodi.wiki/view/Settings#Settings_levels

**Comment by SteenKA** [comment]
Got it. Looks nice.
Since DVBViewer have users from many contries (Russia, China,...) I suggest considering making Arial the default font. 
Thanks

**Comment by manuelm** [comment]
I'm neither in charge of estuary nor anything outside of the PVR in general. So I'm the wrong person for this issue. You might want to open a issue in the Kodi bugtracker https://trac.kodi.tv/ but I doubt this issues justifies a change of the default font. Chinese and other users have to change the font aswell.

**Comment by SteenKA** [comment]
I won't go further with this. I consider the problem solved. How to mark as solved?
I will write a note about it in one of the help files to Xepg and make a new post in the forum.

**Comment by manuelm** [comment]
Just close it :-)
