### ISSUE TITLE
Undefined symbol: GetStreamTimes

### ISSUE THREAD

**Issue by kafisc** [manuelm/pvr.dvbviewer#16]
Kodi (18.0-ALPHA1 Git:36b44e4). Platform: Linux x86 64-bit (Milhouse Generic #0813)
Latest working Version: Milhouse Generic #0803

Log:
ERROR: Unable to load /usr/lib/kodi/addons/pvr.dvbviewer/pvr.dvbviewer.so.3.1.0, reason: /usr/lib/kodi/addons/pvr.dvbviewer/pvr.dvbviewer.so.3.1.0: undefined symbol: GetStreamTimes

**Comment by CiNcH83** [comment]
See [here](https://forum.kodi.tv/showthread.php?tid=319538). No solution for now. Other PVR add-ons are broken as well. According to code docu, this will be fixed in Kodi code. Hopefully soon...

**Comment by manuelm** [comment]
fixed with https://github.com/manuelm/pvr.dvbviewer/commit/1f31807118d2df7504774ad0db50370d7aaf386d
