### ISSUE TITLE
line breaks in EPG description ignored

### ISSUE THREAD

**Issue by nexusle** [manuelm/pvr.dvbviewer#17]
I've noticed, that line breaks in EPG show descriptions seems to be ignored. I've setup some of them in Xepg to optimize the readability. In Kodi these line breaks are ignored. Could you please fix this?

I use DVBViewer addon on Kodi 18

**Comment by manuelm** [comment]
@nexusle should be fixed. In case you're using windows you can download builds from: https://ci.appveyor.com/project/manuelm/pvr-dvbviewer/build/master-5a1520c

**Comment by nexusle** [comment]
Hi Manuel,

sorry for the late answer. Yes, this fixed it. But I use LibreELEC in Odroid and Raspberry primary. When will this change appear in the nightly builds?

**Comment by manuelm** [comment]
I've just bumped the version. 3.3.3 includes the fix and I'll do a backport for Krypton as well.
No idea about LibreELEC nightlies, but I assume they will include the fix as well.
