### ISSUE TITLE
Minimalanforderung neues Update auf Version 2.4.14-Krypton

### ISSUE THREAD

**Issue by Paule84** [manuelm/pvr.dvbviewer#19]
Hallo,
ist es möglich auch wieder DVBViewer Recording Service mit der Version 1.31 laufen zu lassen?
Nachdem update des Addons auf 2.4.14 verbindet er nicht mehr mit dem Recording Service und verlangt minmal die Version 1.33. des Services.
Danke.

**Comment by manuelm** [comment]
Nein, ist nicht mehr möglich. 1.33 wird zwingend benötigt: https://github.com/manuelm/pvr.dvbviewer/commit/01550fccd89d33f2a24b2f5a6535ff6540fb29d2

**Comment by Paule84** [comment]
Ok, dann werde ich nen update durchführen. in der 18er Version von Kodi wird dann auch noch die alten Version unterstützt oder gleich auf 2.0 und höher updaten?

**Comment by manuelm** [comment]
from https://forum.kodi.tv/showthread.php?tid=312691&pid=2597992#pid2597992:
>  Small update: Leia will require 1.33.2 or above. Kodi M* might require DMS.
