### ISSUE TITLE
Playback Time isn't correct

### ISSUE THREAD

**Issue by kafisc** [manuelm/pvr.dvbviewer#21]
I've an issue with the playback time of the latest builds with pvr-dvbviwer on the latest milhouse build #0102. The remaining time is flipping arround and is showing strange values. The lates working build without this behavior is build #1227.
![screenshot001](https://user-images.githubusercontent.com/27443329/34542664-c98f76f0-f0dd-11e7-8dba-379dfe292ed7.png)

**Comment by manuelm** [comment]
Yeah I know. As of now no solution known. See the discussion at https://github.com/xbmc/xbmc/pull/13228 further below

**Comment by manuelm** [comment]
@FernetMenta this is regarding the GetStreamTimes problems we discussed a few weeks ago in https://github.com/xbmc/xbmc/pull/13228.

I've setup a demo for you which plays a previously dumped stream. It doesn't actually do any timeshifting but for demo purpose that's enough. The demo is at https://github.com/manuelm/pvr.demo

You'll notice that as soon as the playback (of any channel) starts the current playtime jumps. The actual time it jumps to seems related to the current system time.

If you disable "timeshift support" (https://github.com/manuelm/pvr.demo/blob/master/src/StreamReader.cpp#L58) the playtime is ok as it's calculated based on the EPG entries.

**Comment by FernetMenta** [comment]
@ksooo I hardly remeber this. Did you fix the circular dependency in the time calculation of pvr?

**Comment by ksooo** [comment]
Yes, I did.

**Comment by FernetMenta** [comment]
@ksooo you don't assume that startme matches with start of epg, do you?

**Comment by ksooo** [comment]
Not at all.

**Comment by manuelm** [comment]
Btw if you change the stream URL (https://github.com/manuelm/pvr.demo/blob/master/src/client.cpp#L385) to some other (local or remote) video the playtime get's calculated correctly. So to me this is about the PTS values inside the dumped stream.

**Comment by FernetMenta** [comment]
I see the problem now. Due to reduced analysis time for pvr *.ts streams, ffmpeg does not complete analysis of the file/stream and does not start at pts zero.
I am thinking about a solution ...

**Comment by junias1993** [comment]
Is there any update for Kodi Leia Alpha 1?

**Comment by manuelm** [comment]
@FernetMenta do you have any updates for us? Afaik two PVRs are affected from this.

**Comment by FernetMenta** [comment]
still on the list of todos

**Comment by FernetMenta** [comment]
can you test this?
https://github.com/xbmc/xbmc/pull/13633

**Comment by manuelm** [comment]
The playtime jumping seems to be fixed, however after playback the current EPG tag and the available timeshift time seems to be wrong. e.g. with my demo:

Playing the channel with epg tag ending at 17:28
![guide](https://user-images.githubusercontent.com/357694/37243654-6ee21c70-247d-11e8-8127-03c852a62904.png)

results in an endtime at 16:20 (no idea where this value comes from) and a very high timeshift value.
![guide2](https://user-images.githubusercontent.com/357694/37243649-511edaa2-247d-11e8-838a-95f10cfaa3e8.png)

If the demo EPG tags would have different names you would see the current EPG tag has jumped a few hours into the future.

And opening the EPG again highlights an EPG tag a few hours later:
![guide3](https://user-images.githubusercontent.com/357694/37243650-539fba80-247d-11e8-804f-9d9adbfa2f9f.png)

**Comment by FernetMenta** [comment]
pr updated, can you test again?

**Comment by FernetMenta** [comment]
you have to set starttime in UTC!

**Comment by manuelm** [comment]
Sorry for late reply. Yes, I'm using UTC/GMT everywhere. Just tested again and on playback all time values are correct now. Thank you very much.

Seeking twice results in some weird time values and breaks after that. No idea if that's due to the API changes:
![guide4](https://user-images.githubusercontent.com/357694/37494548-945d1150-28a9-11e8-8e03-4804ec194d0c.png)

**Comment by ksooo** [comment]
The timeshift offset value in brackets after timeshift current time looks weird...

**Comment by manuelm** [comment]
Yeah. Also seeking to the start makes the bar jump back to the current time instead of staying in the past.

**Comment by manuelm** [comment]
I'm also seeing a lot of
```
23:53:55.005 T:139621174327040   DEBUG: CVideoPlayer::CheckContinuity - resync backward :2, prev:5381888.888907, curr:4401888.888904, diff:-980000.000003
23:53:55.005 T:139621174327040   DEBUG: CVideoPlayer::CheckContinuity - update correction: -980000.000003
23:53:55.813 T:139621174327040   DEBUG: CVideoPlayer::CheckContinuity - resync backward :2, prev:6361888.888910, curr:5381888.888907, diff:-980000.000003
23:53:55.813 T:139621174327040   DEBUG: CVideoPlayer::CheckContinuity - update correction: -980000.000003
```

**Comment by ksooo** [comment]
There must be still something wrong, then. No problems with pvr.hts (tvheadend) here.

**Comment by FernetMenta** [comment]
https://github.com/xbmc/xbmc/pull/13654

**Comment by manuelm** [comment]
A bit better but still no seeking happens: https://manuel.mausz.at/out2.ogv

**Comment by FernetMenta** [comment]
I merged the updated pr. can you try again?

**Comment by manuelm** [comment]
Yeah, everything is working again! Thank you very much.
