### ISSUE TITLE
DVB-T2 - no sound when HA-AAC

### ISSUE THREAD

**Issue by cyberreality** [manuelm/pvr.dvbviewer#22]
not sure whether issue of this plugin. i'm using dvbviewer server as a backend for kodi v18
when playing live dvb-t2 stream with ha-aac codec i have no sound but no problem when record same stream and played later.

would be possible to implement somethink like caching as it was in kodi v16 in pvr?

**Comment by manuelm** [comment]
Not PVR related as it isn't doing any demuxing. That's done by ffmpeg.

**Comment by waldschaefer** [comment]
Hi,
i have also tested the last builds from Kodi 18.0-ALPHA together with the DVBViewer PVR Addon on an Android device. I am using also the latest DVBViewer Media Server.

I have found a similar problem as described above. To play a recording from the DVBViewer Media Server with the PVR-Addon ist working fine. But playing any live channel, there is no audio.

In my understanding, when playing any recording the same data are deliverd from the server as when playing from a live channel ? Or is there any difference ?

When i am using the latest stable Kodi release v17.1, playing any live channel with the PVR-Addon is working also fine.

I guess either the ffmpeg implementation in kodi 18.0 alpha is still incomplete, or the PVR add-on is not working properly with the alpha version yet.

**Comment by manuelm** [comment]
> In my understanding, when playing any recording the same data are deliverd from the server as when playing from a live channel ?

The PVR does basically the same for both, yes. Fetching data (usually in TS format but the PVR doesn't care) from the DMS and passing the data onward to Kodi.

**Comment by waldschaefer** [comment]
That is strange.
Same DMS, same Addon. With Kodi 17.3 audio, but with kodi 18.0 not.
I will test this also on a Windows 10 system.

**Comment by manuelm** [comment]
It might be related to #21, especially comment https://github.com/manuelm/pvr.dvbviewer/issues/21#issuecomment-363758741 about the reduced analyses time.

If you can dump me a about 20mb of live stream from the DMS (e.g. using curl) I can create a small test case for the Kodi team.

**Comment by waldschaefer** [comment]
How can i save a DVB-T live stream from the DMS ? Using the Web-Interface ?

**Comment by manuelm** [comment]
Yes, by downloading the stream instead of opening with a video player. You can use tools like curl or wget. Just make sure to stop it after a few seconds so it doesn't get too big.

**Comment by waldschaefer** [comment]
Ok. I will do that.
