### ISSUE TITLE
EDL (comskip) support

### ISSUE THREAD

**Issue by popy2k14** [manuelm/pvr.dvbviewer#25]
Hey.

Since DVBViewer itself doesnt support EDL we cant get edl informations directly from the DMS api.
I have searched for a workaround to feed the .edl files direcly into kodi and found a working one in the pvr.hdhomerundvr plugin, see here:

Issue: https://github.com/djp952/pvr.hdhomerundvr/issues/18
Function GetRecordingEdl: https://github.com/djp952/pvr.hdhomerundvr/blob/master/src/pvr.cpp

When you look at the issue and the function GetRecordingEdl() they have just made a workaround to "sideload" the .edl file from a file share directory which is confifured in the addon setting.

I'll think until DVBViewer DMS supports edl officially this could be the way to go.

What do you think about it?

PS.: Have builded the mediaportal addon to add an feature but dont know how to build this addon in windows, can you please give me some hints, than ill could look into it.

Keep up the good work
thx

**Comment by popy2k14** [comment]
Have it already running and working.
PR comes soon...

**Comment by popy2k14** [comment]
Thx,  for the info regarding the sideload api of DMS. I have it implemented now that it loads the edl from a specified folder in settings. It works as it should on my two Windows clients. 

One question, I'll have forked the kodi pvr addon directly and not yours. Is it also ok to send the PR directly to the kodi pvr repo? 

Also my patch is based on the latest krypton branch (v2.4.14), hope this is ok?

**Comment by popy2k14** [comment]
Have made a PR to the offical repo: https://github.com/kodi-pvr/pvr.dvbviewer/pull/70
If that doesnt work i will send you to xour fork a PR.

**Comment by manuelm** [comment]
As said it's the wrong repo + wrong branch. However I hope it's ok if I just take your changes and adapt + commit them.

**Comment by popy2k14** [comment]
I will merge it in my local master an make an PR...

**Comment by manuelm** [comment]
I actually have a lot of style problems with your PR and reviewing would take me a lot of time I'd rather spent on something else. I do know that you might don't like this, but I'd really just take your changes and adapt them accordingly myself.

**Comment by popy2k14** [comment]
ok, no problem take it :-)
Tried to merge it manually to my local master but settings.xml changed and i am not familiar with the leia format of it. So, it better you take the code parts and merged it so it will find its way into the official addon repo.

I will post my Krypton addon in the forums, just i anyone (like me) using krypton rather than leia.

PS.: Please give credits to me in addon.xml,

**Comment by popy2k14** [comment]
Here is the PR for leia: https://github.com/kodi-pvr/pvr.dvbviewer/pull/72

**Comment by manuelm** [comment]
Thanks. But I won't add it that way. I talked with the DMS developers and we agreed that we'll load the EDL using the DMS API. So I'm sorry for your extra work.

**Comment by popy2k14** [comment]
ok, that's bad. Have spent a lot of time in it :-(
When will DMS can deliver the EDL through the api?

**Comment by manuelm** [comment]
Probably with the next minor release. But there isn't even an internal version available yet.

**Comment by popy2k14** [comment]
Will check travic build errors and make it build able (in my VS it is).

Why not using this approach of sideloading edl until the DMS side is ready?

**Comment by manuelm** [comment]
> Will check travic build errors and make it build able (in my VS it is).

I wouldn't bother. I've just pushed a bunch if fixed and changes your code is most probably incompatible with.

> Why not using this approach of sideloading edl until the DMS side is ready?

First of all a DMS release is going to happen before Leia. So there's no need to rush at the PVR side. And you are happy with your custom made version for Krypton.

And second: The network directory approach is just wrong. It's incompatible with multiple recording directories, which is common. And it adds an additional network protocol which needs to be setup and might block the whole PVR. At the PVR side I'm very much avoiding adding additional dependencies.

**Comment by manuelm** [comment]
Not yet. However I've migrated the existing timers (one-time and repeated) to the new types and fixed a bunch of bugs. Hopefully without adding new ones :-)

**Comment by popy2k14** [comment]
ahh i see. thx for the info.
Would be nice to get "Suchvorgaben" feature, thats the only thing i am missing that the WAF goes high again.

Keep up the good work
pOpY
