### ISSUE TITLE
No direct Recording 

### ISSUE THREAD

**Issue by SkyBird1980** [manuelm/pvr.dvbviewer#26]
Don't know if its new in the new alpha, but direct recording (using recording button) isn't possible. Also Direct recording using the EPG isn't possible. Only if you set a new timer it works.

Had no debug loggin enabled, but i think this will help also.

[https://paste.ubuntu.com/p/RzytgfDxdb/](url)

I think this is the Problem:

`19:29:23.900 T:4568 ERROR: CPVRTimerType::CreateFromAttributes unable to resolve timer type (0x0, 0x40000b, 46601215) 19:29:23.900 T:4568 ERROR: PVR::CPVRTimerInfoTag::CreateFromEpg - unable to create any epg-based timer type`

Linked Commit: 
[https://github.com/manuelm/pvr.dvbviewer/commit/15e54bb232a74489fbcf99368961a18da5abe426](url)

**Comment by manuelm** [comment]
@ksooo I've added a non-manual timer for one-shot epg recordings (https://github.com/manuelm/pvr.dvbviewer/blob/master/src/Timers.cpp#L143) however the scheduled timers are not shown in the EPG guide as before. There used to be a recording icon if a scheduled timer spans an EPG tag.

During timer transfer I've to convert the one-shot epg back to the manual types as the DVBViewer backend doesn't support recording based on EPG tags. So I do not know if a timer has been scheduled either manually or by using an EPG-tag.

Is this how it's intended to be?

**Comment by manuelm** [comment]
@SkyBird1980 should be fixed with v3.4.3. If you are running Windows you can download the new version at https://ci.appveyor.com/project/manuelm/pvr-dvbviewer -> choose your architecture -> artifacts.

**Comment by SkyBird1980** [comment]
confirmed for Windows x64 👍
