### ISSUE TITLE
timeshift buffer dialog doesn't allow escaping from special://userdata

### ISSUE THREAD

**Issue by manuelm** [manuelm/pvr.dvbviewer#3]
see title

**Comment by J-Peters** [comment]
Hi,

I am using Kodi 14.2 Helix with DVBViewer Client 1.9.24, DVBViewer Pro Recording Service 1.31.0.0 Beta (works properly, Win 7 Pro 64 SP1, TechniSat CableStar Combo HD CI, AzureWave Driver DTV USB TV-Box 7070).

Under "Settings > Advanced" one can enter a Timeshift buffer path, double click on the text "special://userdata/addon_data/pvr.dvbviewer". But this does NOT offer folders or paths for selecting one. Instead, you can create a new folder manually, but NOT every path will be accepted as expected:

1st example: D:\Users\Public\TVTimeShift
2nd example: \\Public\TVTimeShift (means an existing shared network directory/path)

The error message Pops up: <Translated from German> "This path can't be created! Please ensure that the selected folder is not write-protected (writeable) and the new path name is valid".

How to set a Timeshift buffer path, using an existing folder or shared network directory?

Many thanks in advance, and kind regards,
J-Peters

**Comment by manuelm** [comment]
Until this is fixed the only way to set a path outside of the userdata folder is to manually specify the path inside the settings.xml file. As far as I remember the file is also located in special://userdata/addon_data/pvr.dvbviewer

**Comment by J-Peters** [comment]
Hi Manuel,

I tried to modify the file "settings.xml" accordingly, but it doesn't work. Please provide me with a sample (or a pattern) that does work properly - either an UNC path or a Windows directory (folder).

Many thanks in advance, and kind regards,
J-Peters

**Comment by manuelm** [comment]
I'm using: `<setting id="timeshiftpath" value="D:\Recorded TV\TempRec\" />`

never tried UNC
