### ISSUE TITLE
GetStreamTimes API function needs to be implementet - timeshift

### ISSUE THREAD

**Issue by kafisc** [manuelm/pvr.dvbviewer#30]
The GetStreamTimes API function needs to be implementet in order to fully functioning with future kodi builds (milhouse builds). The timeshift button is gone since the kodi beta 2 update..

See https://forum.kodi.tv/showthread.php?tid=298462&pid=2761839#pid2761839

**Comment by manuelm** [comment]
https://github.com/manuelm/pvr.dvbviewer/blob/master/src/client.cpp#L357

Wrong PVR?

**Comment by kafisc** [comment]
No it's not. I mean we have the same problem here.

**Comment by manuelm** [comment]
Just had some time to verify. Timeshift is working as intended.
