### ISSUE TITLE
GetStreamReadChunkSize api parameter as a user setting

### ISSUE THREAD

**Issue by puenktchen** [manuelm/pvr.dvbviewer#31]
Hi,
since Leia, when starting live tv or switching channels i get random picture freezes or sometimes buffering.
This is on Nvidia Shield with Gigabyte Network and never happens with Krypton.

A possible solution could be the proper implementation of the GetStreamReadChunkSize parameter as a user setting or with a fixed value of  64K. It's already implemented in Tvheadend kodi-pvr/pvr.hts@496a8b1
Can you please do something similar for the DVBViewer addon?!

**Comment by manuelm** [comment]
Added in https://github.com/manuelm/pvr.dvbviewer/commit/15ef0a80b4a4ac10c381beff84930813066d0b0a. Part of 3.6.7
