### ISSUE TITLE
Kodi crash after resume from standby

### ISSUE THREAD

**Issue by popy2k14** [manuelm/pvr.dvbviewer#34]
I had the issue on two clients. Sadly no debug log was enabled.
But last notification i have seen was "DVBViewer client" and also last log message is from the dvbviewer addon. 

Dont know if its an issue of the addon or kodi.
Attached the crash dump.

@manuelm can you please look into it. Tried to open it but didnt get the line where it crashes because of lacking pdb files.

[kodi_crash_pvr.zip](https://github.com/manuelm/pvr.dvbviewer/files/2376393/kodi_crash_pvr.zip)

**Comment by manuelm** [comment]
Please extrat the relevant stacktraces for me. My windows development vm is broken

**Comment by popy2k14** [comment]
It needs the kodi.pdb, which i currently does'nt have.
Need to build kodi to get one...

**Comment by manuelm** [comment]
Actually I don't care much about my windows dev system. Been using Linux as main system since more than 15 years now. The only software I develop that runs on Windows is this PVR :-)

PDB for Beta 2 is available at http://mirrors.kodi.tv/releases/windows/win32/
My continous integration builds on AppVeyor are `RelWithDebInfo` builds. So pdb for the PVR is included.

**Comment by popy2k14** [comment]
Never happened again with 3.7.0 on two clients. Maybe the issue was because of an self built addon. I'll Think this could be closed.  If the issue comes back I will open a new one.

**Comment by manuelm** [comment]
You can also reopen an already closed issue. No problem.

**Comment by popy2k14** [comment]
@manuelm 
It happend again with 3.7.0 on one client after resume.
Kodi just closed itself.
I have again an stack trace, see attachment.

Which information do you need and how do ill get them in VS2017.
Sorry, but i am not so familiar with analyzing .dmp stacktraces.

I hade to cut the log because it was to big.

[kodi_crash_after_resume.zip](https://github.com/manuelm/pvr.dvbviewer/files/2404990/kodi_crash_after_resume.zip)

**Comment by manuelm** [comment]
Me neither. Also I'm traveling for the next week.

**Comment by popy2k14** [comment]
@manuelm:
Sadly had this crash after resume from standby again in beta3.
Now i was able to successfully debug the crash dmp in Visual Studio 2017 and the beta 3 pdb.
It is related to PVR.

The exception is the following:
`Ausnahmefehler bei 0x00007FF789D996A0 (kodi.exe) in kodi_crashlog-18.0-BETA3 Git_20181002-c2e1b316f5-20181013-231740.dmp: 0xC0000005: Zugriffsverletzung beim Lesen an Position 0x0000000000000010`

It occured on line 77 in file "NetworkWin32.cpp" on the return statement of this function:

`std::string CNetworkInterfaceWin32::GetCurrentIPAddress(void) const
{
  return CNetworkBase::GetIpStr(m_adapter.FirstUnicastAddress->Address.lpSockaddr);
}`

The call stack was:
`>	kodi.exe!CNetworkInterfaceWin32::GetCurrentIPAddress() Zeile 77	C++
 	kodi.exe!CNetworkBase::IsLocalHost(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & hostname) Zeile 194	C++
 	kodi.exe!PVR::CPVRGUIActions::EventOccursOnLocalBackend(const std::shared_ptr<CFileItem> & item) Zeile 1785	C++
 	kodi.exe!PVR::CPVRGUIActions::AllLocalBackendsIdle(std::shared_ptr<PVR::CPVRTimerInfoTag> & causingEvent) Zeile 1750	C++
 	kodi.exe!PVR::CPVRGUIActions::CanSystemPowerdown(bool bAskUser) Zeile 1657	C++
 	kodi.exe!CApplication::CheckShutdown() Zeile 3917	C++
 	kodi.exe!CApplication::ProcessSlow() Zeile 4348	C++
 	kodi.exe!CApplication::Process() Zeile 4300	C++
 	kodi.exe!CXBApplicationEx::Run(const CAppParamParser & params) Zeile 66	C++
 	kodi.exe!XBMC_Run(bool renderGUI, const CAppParamParser & params) Zeile 80	C++
 	kodi.exe!WinMain(HINSTANCE__ * hInst, HINSTANCE__ * __formal, char * commandLine, int __formal) Zeile 125	C++
`
As i already stated, the last thing i see on GUi is an error of the DVBViewer addon and then it crashes.
Here is the log from waking from standby until it crashes: https://paste.ubuntu.com/p/pMswSMPff6/

Can you please look into it to determine its an addon or kodi PVR issue.
It seems my PC has shortly no IP/hostname after waking up and that leads to the crash.
PS.: after restarting kodi, all is working as it should ->also network is immidatlly working.

thx
pOpY

**Comment by manuelm** [comment]
The stacktrace doesn't show any PVR functions.

**Comment by popy2k14** [comment]
ok, thx for the info. So i will open an ticket in kodi.

pOpY

**Comment by popy2k14** [comment]
Done, see here: https://github.com/xbmc/xbmc/issues/14606
