### ISSUE TITLE
Import EPG SubTitle to EpisodeName

### ISSUE THREAD

**Issue by puenktchen** [manuelm/pvr.dvbviewer#35]
Currently you're importing EPG SubTitle into PlotOutline of the Kodi EPG database.
Unfortunately most Kodi skins use EpisodeName to present futher information of a tv show.
I know there's an addon setting to show SubTitle before Description, but this doesn't fullfill the need,
because the description isn't shown everywhere in a skin. For example OSD!
So can you please import SubTitle also into EpisodeName?

**Comment by manuelm** [comment]
The reason I didn't do this right away is the "SubTitle" information in EPG is not always accurate. Sure for series it's almost always right, but for other events it's not. Just some random picks: For F1 sport events on ORF1 there's `F1 The Race` and `F1 Analyze`. Also there's `Sparkasse 3-Länder-Marathon 2018` with `Highlights aus Bregenz` as subtitle. And on Pro7 there's `Galileo` with `Thema u. a.: Convenience in der Gourmetgastronomie, Information, D 2018`. Surely those are not really episodes, are they?

So I don't think such a setting doesn't make much sense in general. Also I do not want to add more settings. There are already way too much. I might consider adding a hidden one however.

**Comment by puenktchen** [comment]
A hidden setting would be fine!
I don't use dvb epg, but xmltv so i have perfect guide data ;-)

**Comment by manuelm** [comment]
Maybe you should push for a more generic solution in DMS. e.g. more EPG that are usually empty unless the information really is accurate. The episode name would be such an information. Accurate information can then be supplied by external tools like XMLTV, XEPG, etc.. So you might want to talk to Griga first.

**Comment by puenktchen** [comment]
Unfortunately that will not happen. There're already several threads in the DVBViewer forum about the possibilities of other epg sources. But to make use of them, they have to change their storing from binary to a SQLite database. Because the DVBViewer developers only use DVB epg, they're reluctant to put any efford into this.

**Comment by puenktchen** [comment]
Is a hidden setting still a possibility?

**Comment by manuelm** [comment]
Let me come back to you. I need to re-read the issue first. However I don't have much spare time right now. Also I remember an issue about hidden settings (settings that aren't referenced in the ui description). Like reading those settings doesn't work at all.
