### ISSUE TITLE
Teletext subtitles as "unknown (external)" resource

### ISSUE THREAD

**Issue by padman74** [manuelm/pvr.dvbviewer#42]
Hi Manuel, 
first a big compliment. I really like the package of DVB Viewer/Media server and your Kodi plugin. I run newest DVB Viewer/Media server software and your 3.7.11 version.
Teletext subtitles are being recorded by the media server successfully. When I play the recorded file in DVBViewer I can select the teletext stream and it shows it correcty.
Although you can record multiple teletexts (on different sites) your Kodi plugin shows always one named "Unknown (external)" and if you select it, no subtitles are shown. 

Regards
Volker

**Comment by manuelm** [comment]
Thanks for the flattery, however teletext is completely handled by the Media Server + Kodi. I'm not doing a single line of code except passing the stream from the Media Server to Kodi. 

It's probably best to talk with Griga from the DVBViewer Team about this.
