### ISSUE TITLE
Matrix nightlies crash since DVBViewer add-on 6.0.0 update

### ISSUE THREAD

**Issue by CiNcH83** [manuelm/pvr.dvbviewer#44]
Since updating to DVBViewer add-on 6.0.0, Matrix nightlies crash during startup. Am attaching a logcat with the crash report.

[LOG](https://www.dropbox.com/s/hq9ax7btagcpy1e/kodi_pvr_crash.txt?dl=1)

**Comment by CiNcH83** [comment]
I just realized that this repo is on 6.2.0. The repo on kodi-pvr is on 6.0.0 ([click](https://github.com/kodi-pvr/pvr.dvbviewer/commits/Matrix)) which is the version provided via the Kodi package manager. Looks like the two repos are not in sync!?

**Comment by SkyBird1980** [comment]
further information: setting is not an integer (from kodi debug log) if you use "admin" and "0000" as password. 
if you disable authorisation just for lan it will crash.

**Comment by CiNcH83** [comment]
There is a 6.0.2 available, see [here](https://github.com/kodi-pvr/pvr.dvbviewer/pull/96). It still does not work though.

**Comment by manuelm** [comment]
Please try 6.0.4. Should be running again

**Comment by CiNcH83** [comment]
Yes. 6.0.4 looks good. Thanks!

**Comment by puenktchen** [comment]
> Yes. 6.0.4 looks good. Thanks!

Have you compiled it yourself?
@manuelm I don't see any update yet. Neither in Kodi nor on http://mirrors.kodi.tv/addons/matrix/

**Comment by CiNcH83** [comment]
You can download the artifacts from Jenkins, see [here](https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.dvbviewer/detail/Matrix/89/artifacts).

**Comment by puenktchen** [comment]
> You can download the artifacts from Jenkins, see [here](https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.dvbviewer/detail/Matrix/89/artifacts).

Thank you!
