### ISSUE TITLE
6.0.4 still crashing kodi

### ISSUE THREAD

**Issue by SkyBird1980** [manuelm/pvr.dvbviewer#45]
Kodi Version: Kodi (19.0-ALPHA1 (18.9.701) Git:20200712-993af2b93a)
Windows 10:  19041.388 so "2004"
DVBViewer Addon Version: pvr.dvbviewer v6.0.4
DVBViewer is on same system
i tryed lan ip and 127.0.0.1
i use admin as user and  1234 as password for dvbviewer web gui.
i only use favourites.

if i use wrong credentials kodi will show "server does not responding right",
if i enter the right credentials kodi will just close.

[kodi.log](https://github.com/manuelm/pvr.dvbviewer/files/4927038/kodi.log)
it's no debug log, but there isn't more. if you still want it just ask.

**Comment by manuelm** [comment]
The last message from your log is:
```
2020-07-15 19:43:41.927 T:4080     INFO <general>: AddOnLog: pvr.dvbviewer: Trying to connect to the backend server...
2020-07-15 19:43:41.938 T:4080    ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 401
2020-07-15 19:43:41.938 T:4080    ERROR <general>: CCurlFile::Open failed with code 401 for http://127.0.0.1:8089/api/version.html:
                                                   
2020-07-15 19:43:41.938 T:4080    ERROR <general>: AddOnLog: pvr.dvbviewer: Unable to open url: http://127.0.0.1:8089/api/version.html
2020-07-15 19:43:41.938 T:4080    ERROR <general>: AddOnLog: pvr.dvbviewer: Unable to connect to the backend server. Error: Error document empty.
2020-07-15 19:43:41.938 T:4080     INFO <general>: AddOnLog: pvr.dvbviewer: Connection to the backend server failed. Retrying in 10 seconds...
```

>  if i enter the right credentials kodi will just close.

I can't see that. Where is the crash?

**Comment by manuelm** [comment]
And upload a debug log please

**Comment by SkyBird1980** [comment]
Sorry, this was after i changed the credentials to nothing. :)
here a debug log of my other machine (cause i use my server as htpc i switched back to 18.7 there).
[kodi.log](https://github.com/manuelm/pvr.dvbviewer/files/4929106/kodi.log)

**Comment by manuelm** [comment]
I can reproduce the crash on Windows 10. My linux environment works though.

**Comment by SkyBird1980** [comment]
So i can offer more maybe? Stacktrace will help?

**Comment by palasinio** [comment]
Same here: https://github.com/kodi-pvr/pvr.iptvsimple/issues/363#issuecomment-660336385
You can find a crashdump there.

**Comment by manuelm** [comment]
Please try https://ci.appveyor.com/project/manuelm/pvr-dvbviewer/builds/34185853 - you can download the build at the artifacts tab after selecting your platform.

**Comment by Shamshala** [comment]
@manuelm Kodi doesn't crash for me with v6.0.5. :+1:  Unfortunately it doesn't play anything via DVBviewer addon due to _One or more items failed to play_ error. :cry: (movies and other video-addons work without issues)

**Comment by manuelm** [comment]
Never seen that message. Live TV, timeshift and recordings are working here.

**Comment by SkyBird1980** [comment]
6.0.5 works correct exept - if the server is not reachable the message is "server does not answer correct" and not "server is not responding" :)

**Comment by manuelm** [comment]
Will take a look tonight or tomorrow night. It's probably also due to the conversation to the new c++ interface.

**Comment by manuelm** [comment]
@SkyBird1980 I'm not able to reproduce this. I'm getting `Server is unreachable` as expected. I assume you are talking about `Server does not respond properly` which would be triggered if the DMS returns an unexpected reply (like connection succeeds but returns an empty response). Can you reliable reproduce this?

**Comment by SkyBird1980** [comment]
okay, after a restart of kodi it works as expected. this was direct after installing the addon and entering the credentials.
so, it was maybe my bad to mention it.

**Comment by palasinio** [comment]
> Please try https://ci.appveyor.com/project/manuelm/pvr-dvbviewer/builds/34185853 - you can download the build at the artifacts tab after selecting your platform.

@manuelm: I confirm, it works now. Big THX!
