### ISSUE TITLE
Media Server Update Problem

### ISSUE THREAD

**Issue by DanielHofmeier** [manuelm/pvr.dvbviewer#46]
The Kodi Plugin stopped working, when DVB Media Server is upgraded to 3.0.0.0. or 3.0.1.0.

**Comment by manuelm** [comment]
Upgraded a few days ago. Still working.

**Comment by cipher2k** [comment]
I upgraded today, no issues so far.

**Comment by DanielHofmeier** [comment]
Issued can be closed. Sorry guys I tested the setup several hours, nothing worked. Then I recognized snow in my satelitte dish, removed it and oh wonder it worked. Sometimes it's the easy stuff.
