### ISSUE TITLE
Disable Info screens

### ISSUE THREAD

**Issue by bccrew** [manuelm/pvr.dvbviewer#47]
Hello, is there a way to disable these information screens? It looks stupid but every time I open Kodi on my android TV, it's giving me about 50 of these messages and it's annoying because I cannot seem to find a way to turn them off :(

![2021-01-06 11 57 16](https://user-images.githubusercontent.com/8138958/104517807-00954e00-55f7-11eb-8103-279fc1c874e7.jpg)

**Comment by manuelm** [comment]
1. I can't read the text. Foreign language.
2. Why is this an issue? I fail to see any defect.
3. The popup is created by Kodi. So try searching in Kodis PVR settings.

**Comment by bccrew** [comment]
Hi, thanks for your reply. I just can't seem to find the setting where I can turn these information screens off. These are messages informing me about recordings that I set through the Web Interface of the Media Server. Also recording that have happened in the past.

**Comment by manuelm** [comment]
https://kodi.wiki/view/Settings/TV/Recording#Display_a_notification_on_timer_updates ?

```
1.5 Display a notification on timer updates
Settings level: Advanced
Description: Displays a notification when timers are added, finished or removed by the backend.
```

**Comment by bccrew** [comment]
Ok, thank you
