### ISSUE TITLE
DVBViewer addon incompatible with Kodi 19.0 for Android.

### ISSUE THREAD

**Issue by Bjornemand** [manuelm/pvr.dvbviewer#48]
after updating to 19.0 on my Android S9+
I lost all connection with my DVBviewer media server. Apparently the addon 3.7.11 (see attached) is suddenly incompatible with Kodi.

![Screenshot_20210228-102252_Kodi](https://user-images.githubusercontent.com/23146920/109414545-af2cfc80-79b3-11eb-9e0d-61b537f5698b.jpg)

Please notify how to get DVBViewer to work with Kodi 19.0 for Android. Did not see any way to roll back to 18.9 Leia in Google Play. 

Thanks and take care

**Comment by manuelm** [comment]
You need to update the addon. No idea why this isn't automatically shipped with the play store version. At least try the "Versions" button or the "uninstall" button. Current version is 7.2.0

**Comment by manuelm** [comment]
Just tried it on my phone myself. Current PVR version can easily by installed in Kodis addon manager. No problems at all.

**Comment by Bjornemand** [comment]
Great Manuel Mausz,

I successfully uninstalled and reinstalled to get version 7.2.0.

Thank you for your amazing quick response. Top service!!!
Have a wonderful Sunday,

Kind regards,

Bjørn AHRENSBACH


søn. 28. feb. 2021 14.46 skrev Manuel Mausz <notifications@github.com>:
