### ISSUE TITLE
Recordings with wrong recording date (solved)

### ISSUE THREAD

**Issue by riot-user** [manuelm/pvr.dvbviewer#49]
After updating Debian Testing also Kodi was updated to 19.0.
All is working, but now the recordings of the dvbviewer media server have all the same wrong date.

**Comment by manuelm** [comment]
Can't reproduce here. Can you paste the output of `http://dms_ip:dms_port/api/recordings.html?utf8=1&images=1` ?

**Comment by riot-user** [comment]
Hello Manuel,

thank you for taking care of the problem. 

I am on holiday and I will send it on sunday.

cu Jo

 
 

Gesendet: Donnerstag, 08. April 2021 um 10:14 Uhr
Von: "Manuel Mausz" ***@***.***>
An: "manuelm/pvr.dvbviewer" ***@***.***>
Cc: "riot-user" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [manuelm/pvr.dvbviewer] Recordings with wrong recording date (#49)


 

Can't reproduce here. Can you paste the output of http://dms_ip:dms_port/api/recordings.html?utf8=1&images=1 ?

**Comment by riot-user** [comment]
No, I am back.
The output is:
58http://192.168.5.102:8090/upnp/recordings/http://192.168.5.102:8090/upnp/thumbnails/video/Das Erste HD (deu)e:\fernseher\luis trenker - der schmale grat der wahrheit_fernsehfilm deutschland 2015_das erste hd (deu).tsLuis Trenker - Der schmale Grat der WahrheitFernsehfilm Deutschland 2015Luis Trenker - Südtiroler Bergsteigerlegende, Schauspieler und Regisseur - reist im Sommer 1948 zu den Filmfestspielen nach Venedig. Er will die Tagebücher Eva Brauns dem amerikanischen Hollywood-Agenten Paul Kohner zur Verfilmung anbieten. Gleichzeitig wird vor dem Münchner Landgericht die Echtheit dieser Tagebücher verhandelt. Die Regisseurin Leni Riefenstahl, Ex-Geliebte von Trenker, fühlt sich durch die darin enthaltene Andeutung, sie sei Hitlers Geliebte gewesen, verunglimpft. * In Rückblenden wird die Geschichte zweier Opportunisten erzählt, die sich, besessen vom Willen nach künstlerischem Erfolg, instrumentalisieren ließen Produziert in HD [16:9] [H.264] [HD] [stereo] [deu] [Dolby Digital 5.1] [deu] mit Audiodeskription [deu] [Teletext subtitles] [deu] [DVB subtitles] [deu] PDC: 18.11. 20:15 (613647)301811972_SM.jpgSUPER RTLe:\fernseher\khumba - das zebra ohne streifen__super rtl.tsKhumba - Das Zebra ohne StreifenWiederholung vom Freitag, 20:15 Uhr. Das kleine Zebra Khumba wird seit seiner Geburt wie ein Außenseiter behandelt, weil seine Streifen nur bis zum Rückenansatz reichen. Nur seine Eltern und seine beste Freundin Tombi halten zu ihm. Als es zu einer lang anhaltenden Dürreperiode kommt, ist der Schuldige für das Unglück schnell ausgemacht: Die äußerst abergläubigen Zebras sind davon überzeugt, dass Khumba für das Ausbleiben des Regens verantwortlich ist und verstoßen ihn aus der Gemeinschaft.2109034770_SM.jpgProSiebene:\fernseher\snitch - ein riskanter deal_action-thriller, usa 2013_prosieben.tsSnitch - ein riskanter DealAction-Thriller, USA 2013Action-Ikone Dwayne "The Rock" Johnson wird zum Spitzel: Johns Sohn wird aufgrund von Drogenbesitz festgenommen und soll ins Gefängnis. Da John ihn vor dem Leben hinter Gittern bewahren will, geht er einen gefährlichen Deal mit der DEA, der Drogenvollzugsbehörde, ein: Für die Freiheit des Sohnes wird er im Gegenzug in ein Drogenkartell eingeschleust und soll Informationen über den Boss beschaffen. Regie: Ric Roman Waugh Drehbuch: Ric Roman Waugh, Justin Haythe Komponist: Antonio Pinto Kamera: Dana Gonzales Schnitt: Jonathan Chibnall Darsteller: Dwayne "The Rock" Johnson (John Matthews) Susan Sarandon (Joanne Keeghan) Jon Bernthal (Daniel James) Barry Pepper (Agent Cooper) Michael Kenneth Williams (Malik) Rafi Gavron (Jason Collins) Melina Kanakaredes (Sylvie Collins) Nadine Velazquez (Analisa) Benjamin Bratt (Juan Carlos 'El Topo' Pintera) [surround sound] [deu]2151848095_SM.jpgTELE 5e:\fernseher\scoop - der knüller_krimikomödie, usa gb 2006_tele 5.tsScoop - Der KnüllerKrimikomödie, USA/GB 2006Regie: Woody Allen. Darsteller: Scarlett Johansson, Woody Allen, Hugh Jackman. Sondra glaubt, sie sieht nicht richtig. Als sie bei einem Trick des Magiers Splendini auf die Bühne geholt wird, erscheint ihr der Geist des verstorbenen Star-Rep..........

**Comment by manuelm** [comment]
You need to quote the text (with ```). Otherwise the xml tags get removed. Or use a paste service

**Comment by riot-user** [comment]
Ok, hope now it works:

 

 

‚<recordings Ver="1">

<rev>64</rev>

<serverURL>http://192.168.5.102:8090/upnp/recordings/</serverURL>

<imageURL>http://192.168.5.102:8090/upnp/thumbnails/video/</imageURL>

<recording id="1084" charset="255" content="16" start="20151118201500" duration="013000" lastmodified="130923532801241379">

<channel>Das Erste HD (deu)</channel>

<file>

e:\fernseher\luis trenker - der schmale grat der wahrheit_fernsehfilm deutschland 2015_das erste hd (deu).ts

</file>

<title>Luis Trenker - Der schmale Grat der Wahrheit</title>

<info>Fernsehfilm Deutschland 2015</info>

<desc>

Luis Trenker - SÃ¼dtiroler Bergsteigerlegende, Schauspieler und Regisseur - reist im Sommer 1948 zu den Filmfestspielen nach Venedig. Er will die TagebÃ¼cher Eva Brauns dem amerikanischen Hollywood-Agenten Paul Kohner zur Verfilmung anbieten. Gleichzeitig wird vor dem MÃ¼nchner Landgericht die Echtheit dieser TagebÃ¼cher verhandelt. Die Regisseurin Leni Riefenstahl, Ex-Geliebte von Trenker, fÃ¼hlt sich durch die darin enthaltene Andeutung, sie sei Hitlers Geliebte gewesen, verunglimpft. * In RÃ¼ckblenden wird die Geschichte zweier Opportunisten erzÃ¤hlt, die sich, besessen vom Willen nach kÃ¼nstlerischem Erfolg, instrumentalisieren lieÃŸen Produziert in HD [16:9] [H.264] [HD] [stereo] [deu] [Dolby Digital 5.1] [deu] mit Audiodeskription [deu] [Teletext subtitles] [deu] [DVB subtitles] [deu] PDC: 18.11. 20:15 (613647)

</desc>

<image>301811972_SM.jpg</image>

</recording>

<recording id="1100" charset="255" start="20151206155000" duration="012500" lastmodified="130938922804212937">

<channel>SUPER RTL</channel>

<file>

e:\fernseher\khumba - das zebra ohne streifen__super rtl.ts

</file>

<title>Khumba - Das Zebra ohne Streifen</title>

<desc>

Wiederholung vom Freitag, 20:15 Uhr. Das kleine Zebra Khumba wird seit seiner Geburt wie ein AuÃŸenseiter behandelt, weil seine Streifen nur bis zum RÃ¼ckenansatz reichen. Nur seine Eltern und seine beste Freundin Tombi halten zu ihm. Als es zu einer lang anhaltenden DÃ¼rreperiode kommt, ist der Schuldige fÃ¼r das UnglÃ¼ck schnell ausgemacht: Die Ã¤uÃŸerst aberglÃ¤ubigen Zebras sind davon Ã¼berzeugt, dass Khumba fÃ¼r das Ausbleiben des Regens verantwortlich ist und verstoÃŸen ihn aus der Gemeinschaft.

</desc>

<image>2109034770_SM.jpg</image>

</recording>

<recording id="1101" charset="255" start="20151206201400" duration="022500" lastmodified="130939117207916304">

<channel>ProSieben</channel>

<file>

e:\fernseher\snitch - ein riskanter deal_action-thriller, usa 2013_prosieben.ts

</file>

<title>Snitch - ein riskanter Deal</title>

<info>Action-Thriller, USA 2013</info>

<desc>

Action-Ikone Dwayne "The Rock" Johnson wird zum Spitzel: Johns Sohn wird aufgrund von Drogenbesitz festgenommen und soll ins GefÃ¤ngnis. Da John ihn vor dem Leben hinter Gittern bewahren will, geht er einen gefÃ¤hrlichen Deal mit der DEA, der DrogenvollzugsbehÃ¶rde, ein: FÃ¼r die Freiheit des Sohnes wird er im Gegenzug in ein Drogenkartell eingeschleust und soll Informationen Ã¼ber den Boss beschaffen. Regie: Ric Roman Waugh Drehbuch: Ric Roman Waugh, Justin Haythe Komponist: Antonio Pinto Kamera: Dana Gonzales Schnitt: Jonathan Chibnall Darsteller: Dwayne "The Rock" Johnson (John Matthews) Susan Sarandon (Joanne Keeghan) Jon Bernthal (Daniel James) Barry Pepper (Agent Cooper) Michael Kenneth Williams (Malik) Rafi Gavron (Jason Collins) Melina Kanakaredes (Sylvie Collins) Nadine Velazquez (Analisa) Benjamin Bratt (Juan Carlos 'El Topo' Pintera) [surround sound] [deu]

</desc>

<image>2151848095_SM.jpg</image>

</recording>

<recording id="1102" charset="255" start="20151206201500" duration="015300" lastmodified="130939098604246093">

<channel>TELE 5</channel>

<file>

e:\fernseher\scoop - der knÃ¼ller_krimikomÃ¶die, usa gb 2006_tele 5.ts

</file>

<title>Scoop - Der KnÃ¼ller</title>

<info>KrimikomÃ¶die, USA/GB 2006</info>

<desc>

Regie: Woody Allen. Darsteller: Scarlett Johansson, Woody Allen, Hugh Jackman. Sondra glaubt, sie sieht nicht richtig. Als sie bei einem Trick des Magiers Splendini auf die BÃ¼hne geholt wird, erscheint ihr der Geist des verstorbenen Star-Reporters Joe. Er will die IdentitÃ¤t des Tarot-Killers enthÃ¼llen, bevor er endgÃ¼ltig abtritt. DafÃ¼r braucht er Sondra und Splendini. Doch der alternde Zauberer ist das reinste NervenbÃ¼ndel... KÃ¶stlicher KomÃ¶dien-Krimi von Altmeister Woody Allen. [16:9] [stereo] [deu]

</desc>

<image>4244513823_SM.jpg</image>

</recording>

<recording id="1103" charset="255" content="16" start="20151207201500" duration="014500" lastmodified="130939957810224255">

<channel>Einsfestival HD (deu)</channel>

<file>

e:\fernseher\immer drama um tamara_(tamara drewe) spielfilm groÃŸbritannien 2010_einsfestival hd (deu).ts

</file>

<title>Immer Drama um Tamara</title>

<info>(Tamara Drewe) Spielfilm GroÃŸbritannien 2010</info>

<desc>

Ewedown in der englischen Grafschaft Dorset - lÃ¤ndlich, beschaulich, idyllisch. Doch als Tamara Drewe in ihr Heimatdorf zurÃ¼ckkehrt, ist es mit der Ruhe vorbei. Aus dem hÃ¤sslichen Entlein ist eine attraktive und erfolgreiche Journalistin geworden. Die Einheimischen, darunter Tamaras Jugendfreund und der Krimiautor, der gemeinsam mit seiner Gattin ein lokales Schriftstellerrefugium betreibt, kÃ¶nnen ihren Augen kaum trauen. Es dauert nicht lange, bis Tamaras Anwesenheit allen die KÃ¶pfe verdreht. Der britische Erfolgsregisseur Stephen Frears hat eine kÃ¶stliche SittenkomÃ¶die inszeniert, bei der es vor Sittenlosigkeit nur so wimmelt. Produziert in HD [16:9] [H.264] [HD] [stereo] [deu] [Dolby Digital 5.1] [deu] [stereo] [deu] [Teletext subtitles] [deu] [DVB subtitles] [deu] PDC: 07.12. 20:15 (255247)

</desc>

<image>3249365415_SM.jpg</image>

</recording>

<recording id="1109" charset="255" content="32" start="20151213142500" duration="004500" lastmodified="130944895806582242">

<channel>3sat HD (deu)</channel>

<file>

e:\fernseher\sir henry morgan - pirat im auftrag seiner majestÃ¤t_film von marc brasse_3sat hd (deu).ts

</file>

<title>

Sir Henry Morgan - Pirat im Auftrag seiner MajestÃ¤t

</title>

<info>Film von Marc Brasse</info>

<desc>

Im 17. Jahrhundert verbreitete der legendÃ¤re Freibeuter Sir Henry Morgan (1635 - 1688) Angst und Schrecken in der Karibik. Vor Haiti fand man das Wrack seines Schiffes. Die Dokumentation "Sir Henry Morgan - Pirat im Auftrag der MajestÃ¤t" berichtet vom Fund des Wracks und erzÃ¤hlt in Spielszenen aus dem Leben Henry Morgans. HD-Produktion Altersfreigabe: 6 [16:9] [H.264] [HD] [stereo] [deu] [stereo] [mul] [stereo] [mis] [Dolby Digital 2.0] [deu] [DVB subtitles] [deu] PDC: 13.12. 14:25 (451481)

</desc>

<image>2758555275_SM.jpg</image>

</recording>

<recording id="1150" charset="255" content="32" start="20151227120000" duration="010000" lastmodified="130956914409652638">

<channel>KiKA HD (deu)</channel>

<file>e:\fernseher\schneewittchen__kika hd (deu).ts</file>

<title>Schneewittchen</title>

<desc>

MÃ¤rchenklassiker/DEFA-MÃ¤rchenklassiker, Deutsche Demokratische Republik 1961 Es war einmal eine schÃ¶ne KÃ¶nigstochter, die man Schneewittchen nannte. Ihre Haut war so weiÃŸ wie Schnee, ihre Wangen so rot wie Blut und ihr Haar so schwarz wie Ebenholz. Nun war aber ihre Mutter gestorben und der KÃ¶nig nahm sich eine neue Frau. Die war gar stolz und eitel und duldete keine SchÃ¶nere im Land. Als aber Schneewittchen heranwuchs und schÃ¶ner wurde als ihre Stiefmutter, befahl diese einem JÃ¤ger, das Kind im Wald zu tÃ¶ten. Der JÃ¤ger hatte Erbarmen und lieÃŸ das MÃ¤dchen laufen. Der KÃ¶nigin erzÃ¤hlte er, dass er ihren Befehl ausgefÃ¼hrt hÃ¤tte. Schneewittchen kam zu den sieben Zwergen, die sie freundlich aufnahmen und vor der KÃ¶nigin warnten, die sicher auf Rache sinnen wÃ¼rde, wenn sie erfÃ¼hre, dass der JÃ¤ger gelogen hatte. Der Zauberspiegel an der Wand, den die KÃ¶nigin tÃ¤glich befragte, wer die SchÃ¶nste im ganzen Land sei, sagte ihr, wo Schneewittchen zu finden war. Als alte Frau verkleidet, versuchte nun die KÃ¶nigin, sich Schneewittchen zu nÃ¤hern, um sie zu tÃ¶ten. Beim dritten Mal gelang ihr das schreckliche Vorhaben. Mit einem vergifteten Apfel schien sie erfolgreich zu sein. Schneewittchen aÃŸ davon und fiel wie tot zu Boden. Die Zwerge legten das MÃ¤dchen, da es noch so schÃ¶n aussah, als sei es am Leben, in einen glÃ¤sernen Sarg. Ein Prinz, der des Weges kam, verliebte sich in die SchÃ¶nheit und bat die Zwerge um den Sarg. Beim Transport zum Schloss des Prinzen stolperten die TrÃ¤ger und das giftige ApfelstÃ¼ck, das Schneewittchen noch immer nicht ganz verschluckt hatte, fiel heraus und sie kam wieder zu sich. GlÃ¼cklich fÃ¼hrte der Prinz das MÃ¤dchen auf sein Schloss. Als die KÃ¶nigin davon erfuhr, zersprang ihr bÃ¶ses Herz und sie fiel tot um. Darsteller: Schneewittchen - Doris Weikow KÃ¶nigin - Marianne Christina Schilling Junger KÃ¶nig - Wolf Dieter Panse JÃ¤ger - Harry Hindemith Alte - Steffie Spira Zwerg Rumpelbold - Arthur Reppert Zwerg Purzelbaum - Jochen Koeppel Zwerg Packe - Georg Irmer Zwerg Naseweis - Fred Delmare Zwerg Puck - Heinz Scholz Zwerg Huckepack - Willi Scholz Zwerg Pick - Horst Jonischkan Regie: Gottfried Kolditz Buch/Autor: GÃ¼nter Kaltofen Kamera: Erwin Anders Musik: Siegfried Tiefensee HD-Produktion [16:9] [H.264] [HD] [stereo] [deu] [stereo] [mul] [stereo] [mis] [Dolby Digital 2.0] [deu] PDC: 27.12. 12:00 (910080)

</desc>

<image>742626551_SM.jpg</image>

</recording>

<recording id="1152" charset="255" content="16" start="20151227145500" duration="012500" lastmodified="130957034405653043">

<channel>Einsfestival HD (deu)</channel>

<file>

e:\fernseher\glÃ¼ck auf umwegen_spielfilm frankreich belgien 2010 (la chance de ma vie)_einsfestival hd (deu).ts

</file>

<title>GlÃ¼ck auf Umwegen</title>

<info>

Spielfilm Frankreich / Belgien 2010 (La Chance de ma Vie)

</info>

<desc>

Julien ist fÃ¼r Frauen wie die schwarze Katze, die von rechts kommt: Er bringt UnglÃ¼ck. Sobald sie sich verlieben, passiert ihnen ein skurriles Missgeschick nach dem anderen. Damit schlÃ¤gt Julien jede Frau in die Flucht. Dennoch hat er das Talent, Frauen glÃ¼cklich zu machen - allerdings nur mit anderen MÃ¤nnern, denn er ist einer der erfolgreichsten Eheberater von Paris. Als er die Werbedesignerin Joanna kennenlernt, scheint sich alles zum Guten zu wenden. Bis sie Juliens Eltern kennenlernt, und die Katastrophe ihren Lauf nimmt. Eine mitreiÃŸende KomÃ¶die mit viel franzÃ¶sischem Charme und Esprit, Wortwitz und genialer Situationskomik. Produziert in HD [16:9] [H.264] [HD] [stereo] [deu] [Dolby Digital 5.1] [deu] [stereo] [deu] [Teletext subtitles] [deu] [DVB subtitles] [deu] PDC: 27.12. 14:55 (910263)

</desc>

<image>3790671710_SM.jpg</image>

</recording>

<recording id="1154" charset="255" content="16" start="20151227214500" duration="013000" lastmodified="130957283406162172">

<channel>Das Erste HD (deu)</channel>

<file>

e:\fernseher\kommissar wallander - der feind im schatten_spielfilm groÃŸbritannien deutschland schweden 2015 (wallander - the troubled man)_das erste hd (deu).ts

</file>

<title>Kommissar Wallander - Der Feind im Schatten</title>

<info>

Spielfilm GroÃŸbritannien / Deutschland / Schweden 2015 (Wallander - The troubled Man)

</info>

<desc>

Wallander erhÃ¤lt eine Diagnose, die sein Leben Ã¤ndert: Alzheimer. Bevor er Tochter Linda davon erzÃ¤hlen kann, kommt diese ihm mit einer anderen Nachricht zuvor. Ihr Schwiegervater Hakan, ein ehemaliger U-Bootkommandant, ist spurlos verschwunden. Ohnehin vom Dienst freigestellt, beginnt der Kommissar mit privaten Ermittlungen und stÃ¶ÃŸt auf gut gehÃ¼tete Geheimnisse der Familie von Enke. * Zum Abschluss der BBC-Reihe schlÃ¼pft Kenneth Branagh ein letztes Mal in die Rolle des eigensinnigen Kommissars. Ãœberschattet von einer dÃ¼steren Diagnose, findet er sich in seinem vielleicht persÃ¶nlichsten Fall wieder. Produziert in HD [16:9] [H.264] [HD] [stereo] [deu] [Dolby Digital 5.1] [deu] mit Audiodeskription [deu] [Teletext subtitles] [deu] [DVB subtitles] [deu] PDC: 27.12. 21:45 (910701)

</desc>

<image>1894247532_SM.jpg</image>

</recording>

</recordings>‘

 

 

Von: Manuel Mausz ***@***.***> 
Gesendet: Samstag, 10. April 2021 20:35
An: manuelm/pvr.dvbviewer ***@***.***>
Cc: riot-user ***@***.***>; Author ***@***.***>
Betreff: Re: [manuelm/pvr.dvbviewer] Recordings with wrong recording date (#49)

 

You need to quote the text. Otherwise the xml tags get removed. Or use a paste service

**Comment by manuelm** [comment]
The encoding is messed up. Don't know if its because you're replying with your e-mail instead of the webbased github formular or because it's really messed up. Anyway, can you please also provide a full Kodi debug log? The debug log will list the parsed dates. And please use an external paste service.

**Comment by riot-user** [comment]
Hope now it works::

[recordings.txt](https://github.com/manuelm/pvr.dvbviewer/files/6331602/recordings.txt)

**Comment by manuelm** [comment]
Looks good now. Can you please also provide a full Kodi debug log too? The debug log will list the parsed dates.

**Comment by riot-user** [comment]
Okay:
[kodi.log](https://github.com/manuelm/pvr.dvbviewer/files/6368214/kodi.log)

**Comment by manuelm** [comment]
You haven't enabled debug mode beforehand or forgot to restart Kodi afterwards. See https://kodi.wiki/view/Log_file/Easy Step 1 + 2

**Comment by riot-user** [comment]
Thank you for your passion :-)
[kodi.log](https://github.com/manuelm/pvr.dvbviewer/files/6399356/kodi.log)

**Comment by manuelm** [comment]
Thanks. Search the log file for "Loaded recording entry". Every line will be a recording with the start date listed. You can convert the time format using https://www.epochconverter.com/ into a human readable format.

So looking at the output I fail to see anything wrong on my/PVR side.

**Comment by riot-user** [comment]
But where is the mistake?
Your time stamp is correct (1619209800 ->  Freitag, 23. April 2021 22:30:00 GMT+02:00 DST), but Kodi shows for all recordings:
06.02.2021 23:40:00

**Comment by riot-user** [comment]
and it happened when I updated from Kodi 18 to 19

**Comment by manuelm** [comment]
Don't know. Maybe a bug in Kodi itself. As said in the first comment I can't reproduce the problem myself. Works as expected on all platforms (Windows, Linux, Android). Did you try a fresh install?

**Comment by riot-user** [comment]
Yes, I installed Kodi on my laptop. On all others computres at home it is the same but with a different wrong but always equal date.

**Comment by riot-user** [comment]
All computers are with Debian, but I have one laptop with windows. I will try it there.

**Comment by manuelm** [comment]
Weird. Because I/the PVR passes the timestamp directly to Kodi. So the conversation to human readable format happens inside Kodi. Maybe @phunkyfish might have an idea why Kodi always displays the same date for every recording on your computers?

**Comment by phunkyfish** [comment]
There is a fix required for Debian @basilgello will know more.

**Comment by basilgello** [comment]
Yeah it is an issue with cdatetime topic I backported to 19.0 from 20.0 alpha0 in Debian. @riot-user can you please drop me a message at vasek (d0t) gello (d0g) gmail (d0t) com ? I could not build the VM lab for original bug report (with VDR-VNSI) but if we
can debug it on your machine, that'd be great! :)

**Comment by riot-user** [comment]
Thank you all :-).
With the last Debian update it works again:
kodi-data (2:19.0+dfsg1-2) over (2:19.0+dfsg1-1)
