### ISSUE TITLE
EPG is not loaded at automatic start into TV

### ISSUE THREAD

**Issue by obakuhl** [manuelm/pvr.dvbviewer#50]
Hardware / Software:
- Raspberry 4
- LibreELEC-RPi4.arm-9.2.6 
- Kodi 18.9 (Linux Kernel 4.19.x)
- Version DVBViewer Client Addon: 3.7.11.4
- DVBViewer Media Server Version: 3.1.1.0

I don't know if this is a bug or I missed an option to set.
When Kodi starts and the automatic start setting is set to "TV", Kodi goes directly to TV. For this reason, after the boot of Kodi in the upper right corner "PVR manager is starting up" is displayed and as soon as 100% is reached, the last used TV channel starts. So far everything is fine. However, no EPG data is loaded from the DVBViewer server. Instead of the EPG information it says "No information available" for each channel. As soon as the TV picture is closed (via the stop button) a loading bar appears in the upper right corner again ("Importing guide from clients") and the EPG data is loaded and is then also displayed for each channel.
If the setting of the automatic start of the TV after the boot process of Kodi is not set, first comes "PVR manager is starting up", directly after "Importing guide from clients" and everything is fine.
Is there a possibility that the EPG data is loaded in the background when booting directly into the TV or that the EPG data is loaded first and then the TV picture starts?

Thanks 😁
br Ben

**Comment by manuelm** [comment]
That's a bug in Kodi. The PVR does not know (or care) about such Kodi specific settings. The PVR only provides functions (e.g. to load the EPG) which gets triggered by Kodi.

**Comment by manuelm** [comment]
Also make sure you have disabled `Prevent updates during playback`: https://kodi.wiki/view/Settings/TV/Guide#Prevent_updates_during_playback ?

**Comment by obakuhl** [comment]
Thank you. I have been looking for a solution for weeks and did not guess that the solution might be behind this function.
