### ISSUE TITLE
HD audio stutters every 15 seconds when using the timeshift feature

### ISSUE THREAD

**Issue by jakubklos77** [manuelm/pvr.dvbviewer#6]
Hello
I would like to report an issue when using the timeshift option. The audio stutters every once in a while when watching HD channels. Without timeshift or on RTSP it all works fine.
Could you please check it out? Can I send some logs or help troubleshoot this issue?
Thank you
Jakub

**Comment by manuelm** [comment]
Probably a issue on your side.

The PVR itself does no demuxing at all. The difference between timeshift and Live TV is just all data will be written to disk before reading the file again and passing the data to Kodi.

Additional HD channels are working fine here (and probably on hundreds of other computers).

**Comment by jakubklos77** [comment]
Ok, thank you
