### ISSUE TITLE
RTSP is not working on Kodi 16b5 Windows 10

### ISSUE THREAD

**Issue by weidi** [manuelm/pvr.dvbviewer#8]
RTSP isn´t working in Kodi but VLC can play it on the same machine.

21:48:15 T:11260   DEBUG: Error, could not open file rtsp://johannes:554/?src=1&freq=11464&msys=dvbs2&plts=on&fec=23&pol=h&ro=0.35&sr=22000&mtype=8psk&tnr=1,11464,22000,9750,0,0,3,2,515,511,97,61301,134,0,25,0,1017,1,-1&pids=0,18,97,511,33,515,
21:48:15 T:11260   DEBUG: ffmpeg[2BFC]: Using network protocols without global network initialization. Please use avformat_network_init(), this will become mandatory later.

**Comment by manuelm** [comment]
The PVR isn't doing any demuxing itself. This is true for both types of stream (transport stream and RTSP). Kodi itself is using ffmpeg for demuxing. So this is either a bug in Kodi or in ffmpeg.

In general using TS is preferred over RTSP
