### ISSUE TITLE
no logo if there are äüö in sender title // fixed in DVBViewer Recording Service

### ISSUE THREAD

**Issue by SkyBird1980** [manuelm/pvr.dvbviewer#9]
![screenshot001](https://cloud.githubusercontent.com/assets/4501443/16533385/9e43092e-3fd8-11e6-8e86-29bbd23a778a.png)
![dvbviewer](https://cloud.githubusercontent.com/assets/4501443/16533408/c9bf3712-3fd8-11e6-9182-b650b8264bcf.PNG)

**Comment by manuelm** [comment]
Thanks. Will take a look in august.

**Comment by manuelm** [comment]
From RS 1.33.1 changelog:
> Fix: API: Wrong UTF-8 encoding of channel logo URLs in responses to /api/getchannelsxml.html requests.

Maybe this already fixes the issue. Any change you can check this out?

**Comment by SkyBird1980** [comment]
Yes, it works. Thanks four your support Manuelm :)
![screenshot007](https://cloud.githubusercontent.com/assets/4501443/16745395/e947e23e-47b5-11e6-93ac-2509c1e56510.png)
